spring.application.name=cart-service

# Port
server.port=8082

# SQL Server (Windows Auth)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=product_db;encrypt=false;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
i 